---
application:
  name: "southsiderebels"
  project: "southsiderebelsfootball"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "Postgres"
  version: "12"
routers:
- name: "main-southsiderebels"
  routes:
  - application_name: "southsiderebels"
    paths:
    - "/*"
