version: '3'
services: 
    postgres:
        image: postgres:12-alpine
        ports: 
            - "7654:5432"
        environment: 
            POSTGRES_PASSWORD: 7x566390**U
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
    server:
        build: 
            context: ./server
            dockerfile: .
        volumes: 
            - /app/node_modules
            - ./server/config:/app/config
            - ./server/src:/app/src
            - ./server/test:/app/test
        ports: 
            - "8980:8980"
    client:
        build: 
            context: ./client
            dockerfile: .
        volumes: 
            - /app/node_modules
            - ./client:/app
        ports: 
            - "3000:3000"